name: CI

on: [push]

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    environment: pyday2024
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PYDAY_SERVER }}
          username: ${{ secrets.PYDAY_USER }}
          password: ${{ secrets.PYDAY_PASS }}
          port: ${{ secrets.PYDAY_PORT }}
          script: |
            pwd
            ls -l
            sh deploy.sh
